import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_text_styles.dart';
import '../../../../core/widgets/custom_button.dart';
import '../../../../core/widgets/custom_text_field.dart';
import '../../../auth/data/models/user_model.dart';
import '../../../admin/presentation/providers/user_provider.dart';
import '../providers/dept_users_provider.dart';

/// Dialog for adding or editing an employee (same style as AddEditUserDialog)
class AddEmployeeDialog extends ConsumerStatefulWidget {
  final String departmentId;
  final String departmentName;
  final UserModel? userToEdit;

  const AddEmployeeDialog({
    super.key,
    required this.departmentId,
    required this.departmentName,
    this.userToEdit,
  });

  bool get isEditing => userToEdit != null;

  @override
  ConsumerState<AddEmployeeDialog> createState() => _AddEmployeeDialogState();
}

class _AddEmployeeDialogState extends ConsumerState<AddEmployeeDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _employeeIdController = TextEditingController();

  bool _isLoading = false;
  String? _errorMessage;
  DateTime? _joiningDate;

  @override
  void initState() {
    super.initState();
    if (widget.isEditing) {
      final user = widget.userToEdit!;
      _nameController.text = user.name;
      // Remove +91 prefix for display
      _phoneController.text = user.phone.startsWith('+91')
          ? user.phone.substring(3)
          : user.phone;
      _employeeIdController.text = user.employeeId ?? '';
      _joiningDate = user.joiningDate;
    } else {
      _joiningDate = DateTime.now();
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _employeeIdController.dispose();
    super.dispose();
  }

  Future<void> _saveEmployee() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_joiningDate == null) {
      setState(() {
        _errorMessage = 'Please select a joining date';
      });
      return;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final repository = ref.read(userRepositoryProvider);

      // Format phone to E164 (+91xxxxxxxxxx)
      final formattedPhone = '+91${_phoneController.text.trim()}';

      // Check if phone is unique (for create mode or if phone changed)
      if (!widget.isEditing ||
          (widget.isEditing && widget.userToEdit!.phone != formattedPhone)) {
        final isUnique = await repository.isPhoneUnique(
          formattedPhone,
          excludeId: widget.userToEdit?.id,
        );

        if (!isUnique) {
          setState(() {
            _errorMessage =
                'Phone number "${_phoneController.text}" is already in use';
            _isLoading = false;
          });
          return;
        }
      }

      if (widget.isEditing) {
        // UPDATE mode
        final updatedUser = widget.userToEdit!.copyWith(
          name: _nameController.text.trim(),
          phone: formattedPhone,
          joiningDate: _joiningDate,
        );
        await repository.updateUser(updatedUser);
      } else {
        // CREATE mode - Employee ID is auto-generated by repository
        final newUser = UserModel(
          id: '', // Will be set by Firebase
          name: _nameController.text.trim(),
          phone: formattedPhone,
          role: UserRole.employee, // Fixed role for dept head adding
          departmentId: widget.departmentId,
          departmentName: widget.departmentName,
          employeeId: null, // Auto-generated by repository
          joiningDate: _joiningDate!,
        );
        await repository.createUser(newUser);
      }

      // Invalidate providers to refresh UI
      ref.invalidate(deptEmployeesProvider(widget.departmentId));
      ref.invalidate(userCountProvider);

      if (mounted) {
        Navigator.of(context).pop(true);
      }
    } catch (e) {
      setState(() {
        _errorMessage = e.toString();
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
      child: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.all(24.w),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Title
                Row(
                  children: [
                    Container(
                      padding: EdgeInsets.all(12.w),
                      decoration: BoxDecoration(
                        color: AppColors.primaryBlueExtraLight,
                        borderRadius: BorderRadius.circular(10.r),
                      ),
                      child: Icon(
                        Icons.person_add,
                        color: AppColors.primaryBlue,
                        size: 24.sp,
                      ),
                    ),
                    SizedBox(width: 12.w),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            widget.isEditing ? 'Edit Employee' : 'Add Employee',
                            style: AppTextStyles.h5,
                          ),
                          SizedBox(height: 2.h),
                          Text(
                            widget.departmentName,
                            style: AppTextStyles.bodySmall.copyWith(
                              color: AppColors.primaryBlue,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.close),
                      onPressed: () => Navigator.of(context).pop(),
                    ),
                  ],
                ),

                SizedBox(height: 24.h),

                // Name (uppercase)
                CustomTextField(
                  controller: _nameController,
                  labelText: 'Full Name',
                  hintText: 'Enter full name',
                  prefixIcon: const Icon(Icons.person),
                  inputFormatters: [
                    TextInputFormatter.withFunction((oldValue, newValue) {
                      return TextEditingValue(
                        text: newValue.text.toUpperCase(),
                        selection: newValue.selection,
                      );
                    }),
                  ],
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Name is required';
                    }
                    if (value.trim().length < 3) {
                      return 'Name must be at least 3 characters';
                    }
                    return null;
                  },
                ),

                SizedBox(height: 16.h),

                // Phone (with +91 prefix)
                CustomTextField(
                  controller: _phoneController,
                  labelText: 'Phone Number',
                  hintText: '9876543210',
                  prefixIcon: Padding(
                    padding: EdgeInsets.all(16.w),
                    child: Text(
                      '+91',
                      style: AppTextStyles.bodyMedium.copyWith(
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                  keyboardType: TextInputType.phone,
                  inputFormatters: [
                    FilteringTextInputFormatter.digitsOnly,
                    LengthLimitingTextInputFormatter(10),
                  ],
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Phone number is required';
                    }
                    if (value.trim().length != 10) {
                      return 'Phone number must be exactly 10 digits';
                    }
                    return null;
                  },
                ),

                SizedBox(height: 16.h),

                // Role & Department (Read-only info)
                Container(
                  padding: EdgeInsets.all(16.w),
                  decoration: BoxDecoration(
                    color: AppColors.grey50,
                    borderRadius: BorderRadius.circular(12.r),
                    border: Border.all(color: AppColors.grey200),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.info_outline,
                        color: AppColors.textSecondary,
                        size: 20.sp,
                      ),
                      SizedBox(width: 12.w),
                      Expanded(
                        child: Text(
                          'Role: Employee • Dept: ${widget.departmentName}',
                          style: AppTextStyles.bodySmall.copyWith(
                            color: AppColors.textSecondary,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

                SizedBox(height: 16.h),

                // Employee ID (Auto-generated, read-only)
                CustomTextField(
                  controller: _employeeIdController,
                  labelText: widget.isEditing
                      ? 'Employee ID (Permanent)'
                      : 'Employee ID (Auto-set on save)',
                  hintText: 'Auto-generated 8-char ID',
                  prefixIcon: const Icon(Icons.badge),
                  readOnly: true,
                  enabled: false,
                ),

                SizedBox(height: 16.h),

                // Joining Date Selection
                Text(
                  'Joining Date',
                  style: AppTextStyles.labelMedium.copyWith(
                    fontWeight: FontWeight.w600,
                  ),
                ),
                SizedBox(height: 8.h),
                InkWell(
                  onTap: () async {
                    final picked = await showDatePicker(
                      context: context,
                      initialDate: _joiningDate ?? DateTime.now(),
                      firstDate: DateTime(2000),
                      lastDate: DateTime.now(),
                    );
                    if (picked != null) {
                      setState(() {
                        _joiningDate = picked;
                      });
                    }
                  },
                  child: Container(
                    padding: EdgeInsets.symmetric(
                      horizontal: 16.w,
                      vertical: 16.h,
                    ),
                    decoration: BoxDecoration(
                      color: AppColors.grey50,
                      borderRadius: BorderRadius.circular(12.r),
                      border: Border.all(color: AppColors.grey200),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          Icons.calendar_today,
                          color: AppColors.textSecondary,
                        ),
                        SizedBox(width: 12.w),
                        Text(
                          _joiningDate != null
                              ? '${_joiningDate!.day.toString().padLeft(2, '0')}-${_joiningDate!.month.toString().padLeft(2, '0')}-${_joiningDate!.year}'
                              : 'Select joining date',
                          style: AppTextStyles.bodyMedium.copyWith(
                            color: _joiningDate != null
                                ? AppColors.textPrimary
                                : AppColors.textSecondary,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),

                // Error Message
                if (_errorMessage != null) ...[
                  SizedBox(height: 16.h),
                  Container(
                    padding: EdgeInsets.all(12.w),
                    decoration: BoxDecoration(
                      color: AppColors.errorLight,
                      borderRadius: BorderRadius.circular(8.r),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          Icons.error_outline,
                          color: AppColors.error,
                          size: 20.sp,
                        ),
                        SizedBox(width: 8.w),
                        Expanded(
                          child: Text(
                            _errorMessage!,
                            style: AppTextStyles.bodySmall.copyWith(
                              color: AppColors.error,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],

                SizedBox(height: 24.h),

                // Buttons
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: _isLoading
                            ? null
                            : () => Navigator.of(context).pop(),
                        style: OutlinedButton.styleFrom(
                          padding: EdgeInsets.symmetric(vertical: 14.h),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12.r),
                          ),
                        ),
                        child: const Text('Cancel'),
                      ),
                    ),
                    SizedBox(width: 12.w),
                    Expanded(
                      child: CustomButton(
                        text: widget.isEditing ? 'Update' : 'Create',
                        onPressed: _saveEmployee,
                        isLoading: _isLoading,
                        icon: widget.isEditing ? Icons.check : Icons.add,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
