// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWBnC1UHezzSCxWRiGBLLMvpVzOot1VWQ',
    appId: '1:1075195375632:web:ac6fcb1762492f073a9a95',
    messagingSenderId: '1075195375632',
    projectId: 'silver-sves',
    authDomain: 'silver-sves.firebaseapp.com',
    storageBucket: 'silver-sves.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdijZd_9mn3wE3Y9nGapyjjoVEB9_k70',
    appId: '1:1075195375632:android:4f2d96801655d3903a9a95',
    messagingSenderId: '1075195375632',
    projectId: 'silver-sves',
    storageBucket: 'silver-sves.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM4iqjrEGJmBRJXA96CZvQDELwEPvdf4I',
    appId: '1:1075195375632:ios:6d175d08458af9673a9a95',
    messagingSenderId: '1075195375632',
    projectId: 'silver-sves',
    storageBucket: 'silver-sves.firebasestorage.app',
    iosBundleId: 'com.example.silverSves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM4iqjrEGJmBRJXA96CZvQDELwEPvdf4I',
    appId: '1:1075195375632:ios:6d175d08458af9673a9a95',
    messagingSenderId: '1075195375632',
    projectId: 'silver-sves',
    storageBucket: 'silver-sves.firebasestorage.app',
    iosBundleId: 'com.example.silverSves',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWBnC1UHezzSCxWRiGBLLMvpVzOot1VWQ',
    appId: '1:1075195375632:web:95fe261013f854b63a9a95',
    messagingSenderId: '1075195375632',
    projectId: 'silver-sves',
    authDomain: 'silver-sves.firebaseapp.com',
    storageBucket: 'silver-sves.firebasestorage.app',
  );
}
